#!/usr/bin/env sh

# This is an example wrapper script for the rscon tool running on Linux (and
# probably other Unix-like operating systems). Adapt it to your environment and
# needs, make sure it is executable (chmod 755), and put it somewhere in your
# PATH (e.g., `/usr/local/bin/rscon`).

# Uncomment this line if you experience encoding issues with Umlaut characters
# in file names when the Rendition Server is running on a Windows host.
# export LANG=de_DE.ISO-8859-1

# This line runs the rscon tool, threading through any command line parameters
# that were given to this wrapper script (in the $@ variable). If you didn't
# save your JAR files (usually, rscon.jar and dxrapi.jar) in the specified
# directory `/opt/rs` you have to adapt the path.
java -cp '/opt/rs/*' de.nrw.lav.dips.rscon.ConversionCLI "$@"

# Use the following command instead if you like fancy colored terminal output.
# java -cp '/opt/rs/*' de.nrw.lav.dips.rscon.ConversionCLI "$@" | grep -E --color '^(ERROR|FINISHED)|$'
